version: '3'

services:
  server:
    build:
      dockerfile: ./Dockerfile
      context: . 
    image: server_rust
      container_name: server_rust
      volumes:
        - ./data:/home/data
    restart: always
    ports:
      - "34254:34254/udp"
